server:
  port: 8083

spring:
  application:
    name: rabbitmq-practice
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/midd?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: root

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    # 发布确认
      # 1. 开启“发布确认”：每次发送都会有一个唯一的回调
    publisher-confirm-type: correlated
      # 2. 开启“回退通道”：如果消息路由不到队列，不要丢弃，退回给生产者
    publisher-returns: true
    # 消费端配置
      # 消费端配置
    listener:
        simple:
          prefetch: 1
          acknowledge-mode: auto         # ⭐️ 先改成 auto！让框架自动处理 ACK
          retry:
            enabled: true
            initial-interval: 1000
            max-attempts: 3
            multiplier: 2           # 间隔倍数

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
